Python 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
= RESTART: D:\IA provechar\GabrielaFragancias\scripts\DBF to SQL\geos\google rutas a gf.py
Traceback (most recent call last):
  File "C:\Users\Administrador\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 2118, in _exec_insertmany_context
    dialect.do_execute(
  File "C:\Users\Administrador\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: can't adapt type 'ST_GeomFromText'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\IA provechar\GabrielaFragancias\scripts\DBF to SQL\geos\google rutas a gf.py", line 37, in <module>
    gdf.to_sql("gf.puntos_ruta", engine, if_exists="append", index=False, dtype={"ubicacion": Geography("Point", srid=4326)})
  File "C:\Users\Administrador\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Administrador\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\generic.py", line 3087, in to_sql
    return sql.to_sql(
  File "C:\Users\Administrador\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
  File "C:\Users\Administrador\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\sql.py", line 2018, in to_sql
    total_inserted = sql_engine.insert_records(
  File "C:\Users\Administrador\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\sql.py", line 1567, in insert_records
    raise err
  File "C:\Users\Administrador\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\sql.py", line 1558, in insert_records
    return table.insert(chunksize=chunksize, method=method)
  File "C:\Users\Administrador\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\sql.py", line 1119, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
  File "C:\Users\Administrador\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\sql.py", line 1010, in _execute_insert
    result = conn.execute(self.table.insert(), data)
  File "C:\Users\Administrador\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 1418, in execute
    return meth(
  File "C:\Users\Administrador\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\sql\elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\Administrador\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\Administrador\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 1844, in _execute_context
    return self._exec_insertmany_context(dialect, context)
  File "C:\Users\Administrador\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 2126, in _exec_insertmany_context
    self._handle_dbapi_exception(
  File "C:\Users\Administrador\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\Administrador\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 2118, in _exec_insertmany_context
    dialect.do_execute(
  File "C:\Users\Administrador\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'ST_GeomFromText'
[SQL: INSERT INTO "gf.puntos_ruta" (nombre, ubicacion) VALUES (%(nombre__0)s, ST_GeogFromText(%(ubicacion__0)s)), (%(nombre__1)s, ST_GeogFromText(%(ubicacion__1)s)), (%(nombre__2)s, ST_GeogFromText(%(ubicacion__2)s)), (%(nombre__3)s, ST_GeogFromText(%(ubic ... 55484 characters truncated ... _998)s, ST_GeogFromText(%(ubicacion__998)s)), (%(nombre__999)s, ST_GeogFromText(%(ubicacion__999)s))]
[parameters: {'nombre__0': '2017-08-06T19:45:14.218Z', 'ubicacion__0': <geoalchemy2.functions.ST_GeomFromText at 0x1857b0925d0; ST_GeomFromText>, 'nombre__1': '2017-08-06T20:01:08.787Z', 'ubicacion__1': <geoalchemy2.functions.ST_GeomFromText at 0x1857ade30e0; ST_GeomFromText>, 'nombre__2': '2017-08-06T20:06:26.756Z', 'ubicacion__2': <geoalchemy2.functions.ST_GeomFromText at 0x1857b0c06b0; ST_GeomFromText>, 'nombre__3': '2017-08-06T20:07:27.749Z', 'ubicacion__3': <geoalchemy2.functions.ST_GeomFromText at 0x1857b0c0770; ST_GeomFromText>, 'nombre__4': '2017-08-06T20:08:27.839Z', 'ubicacion__4': <geoalchemy2.functions.ST_GeomFromText at 0x1857b0c0980; ST_GeomFromText>, 'nombre__5': '2017-08-06T20:09:28.898Z', 'ubicacion__5': <geoalchemy2.functions.ST_GeomFromText at 0x1857b0c0aa0; ST_GeomFromText>, 'nombre__6': '2017-08-06T20:10:29.036Z', 'ubicacion__6': <geoalchemy2.functions.ST_GeomFromText at 0x1857b0c0bc0; ST_GeomFromText>, 'nombre__7': '2017-08-06T20:11:29.161Z', 'ubicacion__7': <geoalchemy2.functions.ST_GeomFromText at 0x1857b0c0ce0; ST_GeomFromText>, 'nombre__8': '2017-08-06T20:12:29.287Z', 'ubicacion__8': <geoalchemy2.functions.ST_GeomFromText at 0x1857b0c0e00; ST_GeomFromText>, 'nombre__9': '2017-08-06T20:13:30.354Z', 'ubicacion__9': <geoalchemy2.functions.ST_GeomFromText at 0x1857b0c0f20; ST_GeomFromText>, 'nombre__10': '2017-08-06T20:14:30.446Z', 'ubicacion__10': <geoalchemy2.functions.ST_GeomFromText at 0x1857b0c1040; ST_GeomFromText>, 'nombre__11': '2017-08-06T20:15:30.575Z', 'ubicacion__11': <geoalchemy2.functions.ST_GeomFromText at 0x1857b0c1160; ST_GeomFromText>, 'nombre__12': '2017-08-06T20:16:30.701Z', 'ubicacion__12': <geoalchemy2.functions.ST_GeomFromText at 0x1857b0c12b0; ST_GeomFromText>, 'nombre__13': '2017-08-06T20:17:47.185Z', 'ubicacion__13': <geoalchemy2.functions.ST_GeomFromText at 0x1857b0c13d0; ST_GeomFromText>, 'nombre__14': '2017-08-06T20:33:44.524Z', 'ubicacion__14': <geoalchemy2.functions.ST_GeomFromText at 0x1857b0c14f0; ST_GeomFromText>, 'nombre__15': '2017-08-06T20:49:00.422Z', 'ubicacion__15': <geoalchemy2.functions.ST_GeomFromText at 0x1857b0c1610; ST_GeomFromText>, 'nombre__16': '2017-08-06T21:05:26.649Z', 'ubicacion__16': <geoalchemy2.functions.ST_GeomFromText at 0x1857b0c1730; ST_GeomFromText>, 'nombre__17': '2017-08-06T21:14:51Z', 'ubicacion__17': <geoalchemy2.functions.ST_GeomFromText at 0x1857b0c1850; ST_GeomFromText>, 'nombre__18': '2017-08-06T21:19:00Z', 'ubicacion__18': <geoalchemy2.functions.ST_GeomFromText at 0x1857b0c1970; ST_GeomFromText>, 'nombre__19': '2017-08-06T21:27:51.247Z', 'ubicacion__19': <geoalchemy2.functions.ST_GeomFromText at 0x1857b0c1a90; ST_GeomFromText>, 'nombre__20': '2017-08-06T21:28:51.343Z', 'ubicacion__20': <geoalchemy2.functions.ST_GeomFromText at 0x1857b0c1bb0; ST_GeomFromText>, 'nombre__21': '2017-08-06T21:30:52.429Z', 'ubicacion__21': <geoalchemy2.functions.ST_GeomFromText at 0x1857b0c1cd0; ST_GeomFromText>, 'nombre__22': '2017-08-06T21:32:52.662Z', 'ubicacion__22': <geoalchemy2.functions.ST_GeomFromText at 0x1857b0c1df0; ST_GeomFromText>, 'nombre__23': '2017-08-06T21:34:54.324Z', 'ubicacion__23': <geoalchemy2.functions.ST_GeomFromText at 0x1857b0c1f10; ST_GeomFromText>, 'nombre__24': '2017-08-06T21:36:55.655Z', 'ubicacion__24': <geoalchemy2.functions.ST_GeomFromText at 0x1857b0c2030; ST_GeomFromText> ... 1900 parameters truncated ... 'nombre__975': '2017-08-10T18:17:34.380Z', 'ubicacion__975': <geoalchemy2.functions.ST_GeomFromText at 0x185510b45c0; ST_GeomFromText>, 'nombre__976': '2017-08-10T18:17:50Z', 'ubicacion__976': <geoalchemy2.functions.ST_GeomFromText at 0x185510b4710; ST_GeomFromText>, 'nombre__977': '2017-08-10T18:23:57.320Z', 'ubicacion__977': <geoalchemy2.functions.ST_GeomFromText at 0x185510b4860; ST_GeomFromText>, 'nombre__978': '2017-08-10T18:26:41Z', 'ubicacion__978': <geoalchemy2.functions.ST_GeomFromText at 0x185510b49b0; ST_GeomFromText>, 'nombre__979': '2017-08-10T18:43:29.252Z', 'ubicacion__979': <geoalchemy2.functions.ST_GeomFromText at 0x185510b4b00; ST_GeomFromText>, 'nombre__980': '2017-08-10T18:48:51.229Z', 'ubicacion__980': <geoalchemy2.functions.ST_GeomFromText at 0x185510b4c50; ST_GeomFromText>, 'nombre__981': '2017-08-10T18:49:51.301Z', 'ubicacion__981': <geoalchemy2.functions.ST_GeomFromText at 0x185510b4da0; ST_GeomFromText>, 'nombre__982': '2017-08-10T18:50:51.536Z', 'ubicacion__982': <geoalchemy2.functions.ST_GeomFromText at 0x185510b4ef0; ST_GeomFromText>, 'nombre__983': '2017-08-10T18:51:51.685Z', 'ubicacion__983': <geoalchemy2.functions.ST_GeomFromText at 0x185510b5040; ST_GeomFromText>, 'nombre__984': '2017-08-10T18:52:53.310Z', 'ubicacion__984': <geoalchemy2.functions.ST_GeomFromText at 0x185510b5190; ST_GeomFromText>, 'nombre__985': '2017-08-10T18:53:53.414Z', 'ubicacion__985': <geoalchemy2.functions.ST_GeomFromText at 0x185510b52e0; ST_GeomFromText>, 'nombre__986': '2017-08-10T18:54:54.231Z', 'ubicacion__986': <geoalchemy2.functions.ST_GeomFromText at 0x185510b5430; ST_GeomFromText>, 'nombre__987': '2017-08-10T18:55:54.343Z', 'ubicacion__987': <geoalchemy2.functions.ST_GeomFromText at 0x185510b5580; ST_GeomFromText>, 'nombre__988': '2017-08-10T18:56:55.431Z', 'ubicacion__988': <geoalchemy2.functions.ST_GeomFromText at 0x185510b56d0; ST_GeomFromText>, 'nombre__989': '2017-08-10T18:57:55.680Z', 'ubicacion__989': <geoalchemy2.functions.ST_GeomFromText at 0x185510b5820; ST_GeomFromText>, 'nombre__990': '2017-08-10T18:58:55.827Z', 'ubicacion__990': <geoalchemy2.functions.ST_GeomFromText at 0x185510b5970; ST_GeomFromText>, 'nombre__991': '2017-08-10T18:59:55.962Z', 'ubicacion__991': <geoalchemy2.functions.ST_GeomFromText at 0x185510b5ac0; ST_GeomFromText>, 'nombre__992': '2017-08-10T19:05:56.266Z', 'ubicacion__992': <geoalchemy2.functions.ST_GeomFromText at 0x185510b5c10; ST_GeomFromText>, 'nombre__993': '2017-08-10T19:11:56.330Z', 'ubicacion__993': <geoalchemy2.functions.ST_GeomFromText at 0x185510b5d60; ST_GeomFromText>, 'nombre__994': '2017-08-10T19:17:56.310Z', 'ubicacion__994': <geoalchemy2.functions.ST_GeomFromText at 0x185510b5eb0; ST_GeomFromText>, 'nombre__995': '2017-08-10T19:23:56.455Z', 'ubicacion__995': <geoalchemy2.functions.ST_GeomFromText at 0x185510b6000; ST_GeomFromText>, 'nombre__996': '2017-08-10T19:27:50.365Z', 'ubicacion__996': <geoalchemy2.functions.ST_GeomFromText at 0x185510b6150; ST_GeomFromText>, 'nombre__997': '2017-08-10T19:34:00.368Z', 'ubicacion__997': <geoalchemy2.functions.ST_GeomFromText at 0x185510b62a0; ST_GeomFromText>, 'nombre__998': '2017-08-10T19:40:01.219Z', 'ubicacion__998': <geoalchemy2.functions.ST_GeomFromText at 0x185510b63f0; ST_GeomFromText>, 'nombre__999': '2017-08-10T19:46:37.230Z', 'ubicacion__999': <geoalchemy2.functions.ST_GeomFromText at 0x185510b6540; ST_GeomFromText>}]
(Background on this error at: https://sqlalche.me/e/20/f405)
